# Generated by Django 6.0.5 on 2026-05-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('roll_no', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
